### ISSUE TITLE
[1장 깨끗한 코드] 메서드 추출에 대하여

### ISSUE THREAD

**Issue by woo-chang** [JavaBlooming-In-Spring/CleanCode#1]
1장에서 가장 눈에 들어왔던 내용 중 하나는 `메서드`의 역할과 책임을 간소화하는 것입니다.
그러기 위해서는 `메서드 추출`이라는 리팩토링 방법이 소개되었는데, 실제 프로제트를 진행하면서 메서드 추출 시 습관적으로 클래스 내부의 `private` 메서드로 만들게 되었습니다. 보통 이렇게 추출된 메서드들은 유틸리티 성향을 가지는 메서드들이였고, 다른 클래스에서도 이를 사용하곤 하였습니다.

질문은 다음과 같습니다.
1. `private`, `public` 중 어느 것을 택해야 하는가?
2. 별도의 `유틸리티 클래스`를 생성해서 메서드를 옮기는건 어떤지?
3. 해당 클래스와 관련된 메서드이니 해당 클래스에 둬야 하는가?

**Comment by gusah009** [comment]
**새로운 클래스에서 정의해야 한다**
1. IDE에서 해당 함수에 대해 Util class파일로 가서 보다가 다 보고 창을 끄기만 하면 다시 원래 보던 코드로 돌아와서 이득이다.
2. 해당 클래스가 해야하는 역할이 아니라면 그 코드는 Util 클래스가 해야할 일이기 때문에 유틸리티 클래스를 만드는 것이 맞다.
