### ISSUE TITLE
[5장 형식맞추기] 메서드 내부의 세로 밀집도

### ISSUE THREAD

**Issue by woo-chang** [JavaBlooming-In-Spring/CleanCode#3]
개념적으로 동일한 개념은 밀집시키는 방법은 이해했습니다.

메서드 내부에서도 `지역 변수 선언`, `함수 호출` 등 세부 개념이 달리지는 부분이 존재한다고 생각합니다.
메서드를 한 개념으로 보았을 때 메서드 내부는 모두 밀집시켜야 하는지,
위에서 말한 세부 개념을 `빈 행`으로 분리해야하는지 얘기해보고 싶습니다.

**Comment by gusah009** [comment]
`빈 행`으로 구분될 내용은 함수로 뺄 수 있다고 생각하기 때문에 `빈 행`으로 구분하기 보다 함수로 추출한 뒤 모두 붙이는 게 맞는 것 같습니다.
